name: The-Punisher
author: 54mpenguin
website: https://54mpenguin.com
version: ${project.version}
api-version: 1.13
main: me.fiftyfour.punisher.bukkit.BukkitMain
depend: [LuckPerms]
softdepend: [MVdWPlaceholderAPI]
description: The Spigot side of the Punisher plugin.

commands:
  punish:
    description: opens the punishment menu.
    aliases: [pun, p]
  clearchat:
    description: Clears chat.
    aliases: [cc, chatclear]
  togglechat:
    description: Toggles chat.
    aliases: [tc, chattoggle]
  bold:
    description: sends a chat message in bold or red bold.
    aliases: [b]
  punisherbukkit:
    description: admin commands for the bukkit side of the punisher


permissions:
  punisher.punish.level.0:
    description: allows the player to open the punish gui and issue minimal punishments.
    default: false
  punisher.punish.level.1:
    description: allows the player to issue low level punishments.
    default: false
  punisher.punish.level.2:
    description: allows the player to issue medium level punishments.
    default: false
  punisher.punish.level.3:
    description: allows the player to issue high level, manual punishments.
    default: false
  punisher.clearchat:
    description: allows the player to clear the chat.
    default: op
  punisher.clearchat.bypass:
    description: allows the player's chat not to be cleared on clear chat.
    default: op
  punisher.togglechat:
    description: allows the player to toggle the chat.
    default: op
  punisher.togglechat.bypass:
    description: allows the player to talk when the chat is toggled off.
    default: op
  punisher.bypass:
    description: allows the player to bypass all punishments.
    default: op
  punisher.bold:
    description: allows the player to make their chat appear bold.
    default: op
  punisher.bold.red:
    description: allows the player to make their chat appear red bold.
    default: op
  punisher.bukkit.admin:
    description: allows the player to use bukkit admin commands relating to the punisher.
    default: op